### ISSUE TITLE
Infografía - Realidad Aumentada

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Brisa-4#1]
[Infografía.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Brisa-4/files/10855454/Infografia.pdf)

**Comment by josealfredo79** [comment]
Calificacion???

**Comment by IsraelNicolas61** [comment]
Calificación 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
